name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./SampleUI/SampleUI.sln
    - name: Build
      run: dotnet build --no-restore ./SampleUI/SampleUI.sln
    # - name: Test
    #  run: dotnet test --no-build --verbosity normal